### ISSUE TITLE
freezes Signalk when there is no internet

### ISSUE THREAD

**Issue by sailing12388** [jonaswitt/signalk-pushover-plugin#1]
If we don't have an internet connection and the plugin tries to send a notification, it causes Signalk to freeze.

**Comment by jonaswitt** [comment]
Thanks for the report. I will try to reproduce this when I get a chance.

**Comment by jonaswitt** [comment]
Can't reproduce this, sorry. Here's what the signalk-pushover-plugin plugin outputs for me when sending a push notification fails due to no internet connection:

```
Sep 19 15:29:00 TypeError: fetch failed at Object.fetch (node:internal/deps/undici/undici:11576:11) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async sendPush (/home/pi/.signalk/node_modules/signalk-pushover/index.js:52:29) { cause: Error: getaddrinfo EAI_AGAIN api.pushover.net at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) { errno: -3001, code: 'EAI_AGAIN', syscall: 'getaddrinfo', hostname: 'api.pushover.net' } }
```

This is consistent with my expectations that a failed fetch() does not hang a NodeJS process, the relevant fetch() call is here: https://github.com/jonaswitt/signalk-pushover-plugin/blob/main/index.js#L52

If you have any more supporting evidence that the hang is caused by this plugin, please let me know.
